---
title: "CT_sentenced_analysis"
author: "Jesse Warren"
date: "5/7/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(janitor)
library(data.table)
library(RSocrata)
library(ggplot2)
library(ggrepel)
library(extrafont)
library(ggthemes)
library(reshape)
library(grid)
library(scales)
library(RColorBrewer)
library(gridExtra)
library(viridis)
library(hexbin)
library(sandwich)
library(stargazer)
library(sf)
library(ggpubr)
library(scales)
options(scipen=999)
library(tidyverse)

#load functions from helper files
source("Helper_functions/Data_loading_and_cleaning_functions.R")
```

```{r Load files, message=FALSE, warning=FALSE}
#2 options to load data:
  #1. straight from online open data repository for most up to date data
  #2. from local files (downloaded 5/7/2020)

#option 1.
#load pretrial data from Connecticut open data site  
CT_sentenced_data_URL <- "https://data.ct.gov/Public-Safety/Sentenced-Inmates-in-Correctional-Facilities/um73-fxm4"
#CT_sentenced_raw <- read.socrata((CT_sentenced_data_URL))

#option 2.
#load from local file, in Data/ folder
CT_sentenced_raw <- fread("Data/Sentenced_Inmates_in_Correctional_Facilities.csv")

#fix race names
CT_sentenced_raw$RACE[CT_sentenced_raw$RACE == 'AMER IND'] <- 'Native American'
CT_sentenced_raw$RACE[CT_sentenced_raw$RACE == 'ASIAN'] <- 'Asian'
CT_sentenced_raw$RACE[CT_sentenced_raw$RACE == 'BLACK'] <- 'Black'
CT_sentenced_raw$RACE[CT_sentenced_raw$RACE == 'WHITE'] <- 'White'
CT_sentenced_raw$RACE[CT_sentenced_raw$RACE == 'HISPANIC'] <- 'Hispanic'

#clean names, set variable types, fix dates
CT_sentenced_raw <- CT_sentenced_raw %>% 
  clean_names() %>% 
  mutate(identifier = as.factor(identifier),
         race = as.factor(race),
         gender = as.factor(gender),
         offense = as.factor(offense),
         facility = as.factor(facility),
         detainer = as.factor(detainer),
         download_date = as.Date(download_date, '%m/%d/%Y'),
         latest_admission_date = as.Date(latest_admission_date, '%m/%d/%Y'),
         special_parole_end_date = as.Date(special_parole_end_date, '%m/%d/%Y'),
         identifier = as.character(identifier))

colnames(CT_sentenced_raw)
```

```{r Preliminary descriptive look, cache = TRUE}
#how many observations are there?
nrow(CT_sentenced_raw)

#how many unique people in dataset?
length(unique(CT_sentenced_raw[,"identifier"])) 

#how many unique person-admissions are there (because some people may have multiple admissions)?
nrow(unique(CT_sentenced_raw[,c("identifier","latest_admission_date")])) 

#how many total charges for all the admissions in this dataset?
nrow(unique(CT_sentenced_raw[,c("identifier","latest_admission_date", "offense")]))

#how many unique charges?
length(unique(CT_sentenced_raw[,"offense"]))
```
```{r Why are people in prison graph}
#make a df of charges
sentenced_charges <- unique(CT_sentenced_raw[,c("identifier","latest_admission_date", "offense")]) %>%
  group_by(offense)%>%
  summarise(count = n())%>%
  mutate(tot = sum(count),
         perc = count/tot)

#make a df of top 10 charges.
sentenced_charges10 <- sentenced_charges %>% 
  arrange(-perc) %>% 
  head(10)


#fix up offense
sentenced_charges10$offense <- tolower(sentenced_charges10$offense)
sentenced_charges10$offense <- str_remove(sentenced_charges10$offense, " df")
sentenced_charges10$offense <- str_remove(sentenced_charges10$offense, "  f")
sentenced_charges10$offense <- str_remove(sentenced_charges10$offense, " am")
sentenced_charges10$offense <- str_remove(sentenced_charges10$offense, " bf")
sentenced_charges10$offense <- str_remove(sentenced_charges10$offense, " af")
sentenced_charges10$offense <- str_remove(sentenced_charges10$offense, " cm")

sentenced_charges10$offense <- str_squish(sentenced_charges10$offense)

#Make a factor for ordering the x axis
sentenced_charges10$offense <- factor(sentenced_charges10$offense, levels = sentenced_charges10$offense[order(sentenced_charges10$perc)])

#create graph
ggplot(data = sentenced_charges10, aes(x = offense, y = perc)) + 
  geom_bar(stat = 'identity') +
  theme_minimal() +
  scale_y_continuous(labels = percent) +
  theme(plot.title = element_text(hjust = 0)) +
  labs(x="", y="", caption="These calculations consider all 34,764 unique person-admission-offense observations from 8-22-2017 to 5-7-2020.") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
  ggtitle("Why Are People in Prison? (Top 10 Charges)", subtitle = "Data Available via Connecticut Open Data")
ggsave("Graphs/sentenced_reasons_for_arrest.png", width=7, height=4.5, dpi=900)

#crosstabs
sentenced_charges10
```


```{r Demographics descriptive look}
#create df of unique people
CT_sentenced_people <- unique(CT_sentenced_raw[,c("identifier", "race", "gender")])

#get difference between number of unique people, and number of unique people by race and gender as well to see if some people are being coded multiple times as different races/genders
nrow(CT_sentenced_people) - length(unique(CT_sentenced_raw[,"identifier"])) 

#exclude the people coded with different race and/or genders across the time period.
CT_sentenced_people$dup <- duplicated(CT_sentenced_people$identifier)
CT_sentenced_people_dup <- subset(CT_sentenced_people, dup == "TRUE")
CT_sentenced_people_dup <- CT_sentenced_people_dup[,1]
CT_sentenced_people_deduped <- CT_sentenced_people %>% 
  filter(!identifier %in% CT_sentenced_people_dup)
CT_sentenced_people_deduped <- CT_sentenced_people_deduped[,c(1:3)]

#Define colorblind friendly palettes
# The palette with grey:
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
Pal <- c("#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# The palette with black:
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

#graph
ggplot(data = CT_sentenced_people_deduped, aes(race, fill=gender)) + 
  geom_bar() +
  theme_minimal() +
  scale_fill_manual(name="Gender", values = c("gold", "dodgerblue"), labels=c("Female", "Male")) +
  theme(plot.title = element_text(hjust = 0)) +
  labs(x="", y="Number of Prison Inmates",
       caption="The total number of unique prison inmates in this time period is INSERT; I present data for INSERT here.\n(I exclude 57 individuals who are coded inconsistently by race or gender over time).\nThe dataset codes Hispanic as a race (this is different than, say, the Census methodology).") +
  ggtitle("Gender and Race of Connecticut Sentenced Inmates (INSERT DATE)", subtitle = "Data Available via Connecticut Open Data")
ggsave("Graphs/sentenced_gender_race.png", width=7, height=4.5, dpi=900)

#summary stats - gender
tabyl(CT_sentenced_people_deduped, gender)

#summary stats - race
tabyl(CT_sentenced_people_deduped, race) 

```

```{r Compare race to CT population }
#create race summary df
CT_sentenced_race <- CT_sentenced_people_deduped %>%
  group_by(race) %>%
  summarize(count = n()) %>%
  mutate(total = sum(count)) %>%
  mutate(perc = count/total)


#Manually add the census data, based on an approximation (since ethnicity, race done differently by the census) from (https://www.census.gov/quickfacts/CT) As of 5/6/2020.
race <- c('Asian','Black','Hispanic', 'Native American', 'White')
c_perc <- c(.049, .120, .165, .006, .665)
census <- data.frame(race, c_perc)


#Merge the census and pretrial.
CT_sentenced_race_census <- merge(CT_sentenced_race, census, by="race")


#Reshape
CT_sentenced_race_census <- CT_sentenced_race_census %>%
  gather(source, percent, perc:c_perc)


#Make the plot.
ggplot(data = CT_sentenced_race_census, aes(x = source, y = percent, fill = race)) + 
  geom_bar(stat = 'identity') +
  theme_minimal() +
  scale_fill_manual(name = "Race", values = cbPalette) +  
  theme(plot.title = element_text(hjust = 0)) +
  labs(x="", y="",
       caption="The sentenced inmate population covers 27,786 people who at some point were in DOC facilities 8/22/17-5/7/2020.\n(I exclude 57 individuals who are coded inconsistently by race or gender over time).\nOverall Population data is estimated from the US Census QuickFacts.")+
  scale_y_continuous(labels = percent) +
  scale_x_discrete(labels=c("Overall Population", "Sentenced Inmate Population")) + 
  ggtitle("Overall Connecticut Population vs. Connecticut Sentenced Inmate Population", subtitle = "Data Available via Connecticut Open Data")
ggsave("Graphs/sentenced_race_compare.png", width=7, height=5, dpi=900)
```

```{r View age and race as of 5/7/2020, message=FALSE, warning=FALSE}
#only look at people in jail as of 5/7/2020
CT_5_7_2020 <- subset(CT_sentenced_raw, download_date == "2020-05-07")

#look at median age
median(CT_5_7_2020$age)

#create plot of age and race as of 5/2/2020
ggplot(data = CT_5_7_2020, aes(age, fill=race)) + 
  geom_histogram(breaks=seq(15, 80, by = 1)) +
  theme_minimal() +
  scale_fill_manual(name="Race", values = cbPalette) +  
  theme(plot.title = element_text(hjust = 0)) +
  labs(x="Age", y="Number of Sentenced Inmates",
       caption="This graphs covers only the inmates present in DOC facilities on 5/7/2020.") +
  #scale_y_continuous(limits=c(0,126), breaks=seq(0,126,25))+
  #scale_x_continuous(limits=c(15,81), breaks=seq(15,80,5))+ 
  ggtitle("Age and Race of Connecticut Sentenced Inmates (5/7/2020)", subtitle = "Data Available via Connecticut Open Data")
ggsave("Graphs/sentenced_age_race-05-07-20.png", width=8, height=5, dpi=900)
```

```{r look at length of sentence for people in jail as of 5/7/2020}
#it appears that people with life sentences are coded as having 36897 day sentences (the equivalent of 1010 years). I remove these people from this analysis
#create plot of sentence days as of 5/2/2020
CT_5_7_2020 %>% 
  filter(sentence_days < 36897,
         sentence_days > 0) %>%
  mutate(sentence_years = sentence_days / 365) %>% 
  ggplot(aes(sentence_years, fill=race)) + 
    geom_histogram(bins = 25) +
    theme_minimal() +
    scale_fill_manual(name="Race", values = cbPalette) +  
    theme(plot.title = element_text(hjust = 0)) +
    labs(x="Sentence (Years)", y="Number of Sentenced Inmates",
         caption="This graphs covers only the inmates present in DOC facilities on 5/7/2020.") +
    #scale_y_continuous(limits=c(0,126), breaks=seq(0,126,25))+
    #scale_x_continuous(limits=c(15,81), breaks=seq(15,80,5))+ 
    ggtitle("Sentence Lengths of Connecticut Sentenced Inmates (5/7/2020)", subtitle = "Data Available via Connecticut Open Data")
ggsave("Graphs/sentenced_sentence_length-05-07-20.png", width=8, height=5, dpi=900)

#count people with life sentences
CT_5_7_2020 %>% 
  filter(sentence_days > 36897) %>% 
  distinct(identifier, offense, latest_admission_date) %>% 
  nrow()
```

```{r Plot average sentence by race for all people in dataset}
#remove inconsistently coded people, as done above
CTsentenced_summary_stats <- CT_sentenced_raw %>% 
  filter(!identifier %in% CT_sentenced_people_dup)


#create df with summary stats of duration. remove life sentences, which skew daya
CTsentenced_summary_stats <- CTsentenced_summary_stats[,c("race", "sentence_days", "age")] %>%
    filter(sentence_days < 36897) %>% 
    group_by(race) %>%
    summarise_all(funs(mean,sd,se = sd(.)/sqrt(n()) ))

#plot averages in jail sentence by race
ggplot(CTsentenced_summary_stats, aes(x = race, y = sentence_days_mean)) +
  geom_errorbar(aes(ymin = sentence_days_mean - (1.96 * sentence_days_se), 
                    ymax = sentence_days_mean + (1.96 * sentence_days_se)), width = .5) +
  geom_point() +
  #scale_color_manual(values = cbPalette) +  
  theme_minimal() + 
  theme(plot.title = element_text(hjust = 0)) +
  labs(x="", y="Mean Prison Sentence (Days)", caption="Each observation is for an individual sentence, so some individuals with multiple sentences are included multiple times. (n=9,143,844)\n(I exclude life sentences and individuals who are coded inconsistently by race or gender over time.)\nThe means by race are presented with 95% confidence intervals.")+
  scale_y_continuous(labels = comma, limits = c(0,5000))+
  ggtitle("Mean Prison Sentence by Racial Group", subtitle = "Data Available via Connecticut Open Data")
ggsave("Graphs/sentenced_sentence-race.png", width=7, height=5, dpi=900)
```


```{r test to see how sentence dates are calculated}
CTsentenced_raw_sentence_date_calcs <- CT_sentenced_raw %>% 
  head(50) %>% 
  mutate(end_sentence_date = as.Date(end_sentence_date, "%m/%d/%Y"),
         latest_admission_date = as.Date(latest_admission_date),
         download_date = as.Date(download_date)) %>% 
  mutate(calculated_sentence_date = end_sentence_date - latest_admission_date)


CTsentenced_raw_sentence_date_calcs %>% 
       dplyr::select(download_date, end_sentence_date, latest_admission_date, sentence_days, calculated_sentence_date, offense)
```

